# Generated by Django 3.1.2 on 2024-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('release_date', models.CharField(max_length=1000)),
                ('lte_existst', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
            ],
        ),
    ]
